repositories:
  - name: local-repository
   url: http://localhost:8000/
releases:
  - name: sre-challenge-redis
    namespace: sre-challenge
    chart: oci://registry-1.docker.io/bitnamicharts/redis
    version: 20.1.5
    values:
      - redis-values.yaml
  - name: sre-challenge
    namespace: sre-challenge
    chart: local-repository/sre-challenge
    version: v0.0.7
    values:
      - values.yaml