name: build

env:
  IMAGE_NAME: sre-challenge
  DOCKER_REGISTRY: docker-registry.docker-registry.svc.cluster.local

# Controls when the workflow will run
on:
  # Triggers the workflow on push events only when done on branches
  push:
    tags-ignore:
      - 'v**'
    branches:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # We only have a build job
  build:
    # We run on our arc runners
    runs-on: arc-runner-set
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Run tests
      - name: tests
        run: |
          make unit-tests
      # Build the image and see that it builds
      - name: build
        run: |
          export COMMIT_SHA=${GITHUB_SHA::7}
          make build
      # Step 3: Build the Docker image with cache and push it
      - name: push
        run: |
          export COMMIT_SHA=${GITHUB_SHA::7}
          make push