name: build

env:
  IMAGE_NAME: sre-challenge
  DOCKER_REGISTRY: docker-registry.docker-registry.svc.cluster.local

# Controls when the workflow will run
on:
  # Triggers the workflow on push events only when done on certain tags
  push:
    tags:
      - 'v**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # We only have a build-chart job
  build-chart:
    # We run on our arc runners
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@master
        with:
          name: aethen22org/infra
          ref: chart-base/v1.0.3
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      # Run tests
      - name: build chart
        run: |
          make build-chart